REATE DATABASE codebook_db;

USE codebook_db;

CREATE TABLE users (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(64) NOT NULL
);

USE codebook_db;

CREATE TABLE posts (
post_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
posts LONGTEXT,
user_id INT NOT NULL, 
FOREIGN KEY(user_id) REFERENCES users(id)
);